### PR TITLE
Optional arg to specify cache key instead of using image tag

### PR DESCRIPTION
**Pull request by danajp**
TOPS-2001

### CODE REVIEW

**Comment by pclalv** [comment]
thanks to yesterday's discussion, i totally understand what's going on here. how long are we planning on carrying this fork? do we plan on opening an upstream issue about this?

or, do we need do to it this way? it occurs to me that if we build, say GHR images, with `pack build greenhouse`, then we wouldn't even need this option because the cache key would be the image name/repo name, `greenhouse`. the result would be the same as `docker build -t greenhouse` - we'd end up with an image `greenhouse:latest`. in that case, we'd have to worry about concurrent builds clobbering `greenhouse:latest`. but still, i think it could be useful to think about the cache key problem in terms of an image name. imagine we could do `pack build gcr.io/gh-infra/dajoku/greenhouse:somesha`, and that pack would split on `:` to get the repo name of `gcr.io/gh-infra/dajoku/greenhouse`, and use that as the cache key. that could be sweet.

are we gonna run into issues with concurrent builds no matter what if we pass `--cache-key appname`?

**Comment by pclalv** [comment]
either way, i think we could be worth bringing up with the buildpack people, given that they're making a public tool that doesn't fit our needs. it's not even some kind of crazy obscure need, either.

**Comment by danajp** [comment]
You are correct that this has the same effect as doing `pack build ... greenhouse` every time we build. The problem is the concurrency. We can't have 2 processes using the same docker daemon building the same image tag at the same time. One will end up clobbering the other one.

They've stated in the builpacks slack that pack is really only intended for building images locally. In a cloud environment (like we're operating in), we should be calling the lifecycle directly. In that case, you pass the cache volume/image explicitly, which sidesteps this whole problem. For example https://github.com/knative/build-templates/blob/master/buildpacks/cnb.yaml.

So this is really a short term hack, long term we don't run `pack` in git-receive, we will just call the lifecycle as `pack` does.

**Comment by pclalv** [comment]
okay, sounds good.

so, i'm confused as to the purpose of this hack. is it to help us work around the concurrency issue AND to help us to better utilize the cache?

**Comment by danajp** [comment]
This lets us use the same cache for different commit shas of the same app. Without my change, these two builds would each use their own cache:
- `pack build ... some-app:deadbeef`
- `pack build ... some-app:deaddead`

With my change, they can use the same cache:
- `pack build ... --cache-key some-app some-app:deadbeef`
- `pack build ... --cache-key some-app some-app:deaddead`

**Comment by danajp** [comment]
I've rebased this PR onto the `v0.1.0` tag. And also added a `Makefile` for building the binaries and some notes in the readme.

**Pull request merged**
